/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-tertiary-fixed": "#221b03",
          "on-tertiary-container": "#473f22",
          "tertiary": "#d4c69f",
          "on-error-container": "#ffdad6",
          "secondary": "#e9c349",
          "on-surface": "#c2eae8",
          "surface-variant": "#133b39",
          "surface": "#001716",
          "outline": "#89938d",
          "error": "#ffb4ab",
          "inverse-surface": "#c2eae8",
          "background": "#001716",
          "surface-container-highest": "#133b39",
          "surface-bright": "#183f3e",
          "on-tertiary": "#383015",
          "secondary-container": "#af8d11",
          "primary-container": "#064e3b",
          "on-primary-container": "#80bea6",
          "inverse-primary": "#2b6954",
          "primary-fixed-dim": "#95d3ba",
          "primary": "#95d3ba",
          "tertiary-fixed": "#f0e2ba",
          "outline-variant": "#404944",
          "secondary-fixed-dim": "#e9c349",
          "surface-container-low": "#00201f",
          "on-tertiary-fixed-variant": "#4f4629",
          "tertiary-fixed-dim": "#d4c69f",
          "surface-container-high": "#052f2e",
          "on-primary": "#003829",
          "surface-tint": "#95d3ba",
          "tertiary-container": "#b7aa85",
          "on-background": "#c2eae8",
          "surface-dim": "#001716",
          "on-surface-variant": "#bfc9c3",
          "on-primary-fixed": "#002117",
          "on-secondary": "#3c2f00",
          "inverse-on-surface": "#0d3635",
          "secondary-fixed": "#ffe088",
          "on-secondary-container": "#342800",
          "surface-container": "#002423",
          "on-error": "#690005",
          "error-container": "#93000a",
          "surface-container-lowest": "#001111",
          "on-primary-fixed-variant": "#0b513d",
          "on-secondary-fixed": "#241a00",
          "on-secondary-fixed-variant": "#574500",
          "primary-fixed": "#b0f0d6"
      },
      fontFamily: {
        headline: ["Noto Serif"],
        body: ["Manrope"],
        label: ["Manrope"]
      }
    },
  },
  plugins: [],
}
